project_name: pigeon
builds:
  - id: "{{.ProjectName}}"
    goos:
    - linux
    goarch:
    - amd64
    main: .
    flags:
      - -v 
      - -buildmode=pie
    binary: "{{.ProjectName}}"

dockers:
  - image_templates:
      - "ghcr.io/falcosecurity/{{.ProjectName}}:latest"
      - "ghcr.io/falcosecurity/{{.ProjectName}}:{{ .Tag }}"

release:
  github:
  prerelease: auto
