project_name: pigeon
builds:
  - id: "pigeon"
    goos:
    - linux
    goarch:
    - amd64
    main: .
    flags:
      - -v 
      - -buildmode=pie
    binary: pigeon

release:
  github:
  prerelease: auto
