project_name: pigeon
builds:
  - id: "{{.ProjectName}}"
    goos:
    - linux
    goarch:
    - amd64
    main: .
    flags:
      - -v 
      - -buildmode=pie
    binary: "{{.ProjectName}}"

dockers:
  - image_templates:
      - "ghcr.io/falcosecurity/{{.ProjectName}}"

release:
  github:
  prerelease: auto
